uat:
 username_suffix: .sfdcuat2
 salesforce_host: test.salesforce.com
 salesforce_username: psrefresh@thoughtworks.com.sfdcuat2
 salesforce_password: Salesfunnel@2018!
 salesforce_security_token: axRqqj8AcTfT9y3OieAREe5Tk
 salesforce_client_id: 3MVG9qbIpUScOGtZPySUy.2dxC2rb6JoikSzlLLilpJvRoxcbCvjZ3uQIbgM0j3td357Vax2cesJLZxfeEZsN
 salesforce_client_secret: 7160731565472607176
 salesforce_metadata_cache_duration: 86400
 log_path: /var/log/accounts_service.log
 url: https://uat.accounts-service.thoughtworks.net
 cache_store: accounts_service_uat

prod:
 username_suffix:
 salesforce_host: na32.salesforce.com
 salesforce_username: psrefresh@thoughtworks.com
 salesforce_password: Sl*3UqFp
 salesforce_security_token: HDdIoqCYWdm1sf0EJ5AqtclNX
 salesforce_client_id: 3MVG9Km_cBLhsuPweaY.ngghVGKm2DV0D5IgFL6WWe.3Svv6jCH8.KDzGirO9K6BY6Zrt684enxNEzPoYGnbK
 salesforce_client_secret: 824907496245728533
 salesforce_metadata_cache_duration: 86400
 log_path: /var/log/accounts_service.log
 url: https://accounts-service.thoughtworks.net
 cache_store: accounts_service
